### ISSUE TITLE
💥 Crash in server.js on new channel creation

### ISSUE THREAD

**Issue by RDCH106** [Pezmc/Quiz-Scoreboard#5]
When I try to create a new channel for new scoreboard creation, I receive the following stack trace in server side:

``` console
PS D:\xampp\htdocs\quiz-scoreboard\node> node .\server.js
   info  - socket.io started
Listening on port 25565
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Socket.Writable.end (_stream_writable.js:553:10)
    at Socket.end (net.js:496:31)
    at Static.gzip (D:\xampp\htdocs\quiz-scoreboard\node\node_modules\socket.io\lib\static.js:207:14)
PS D:\xampp\htdocs\quiz-scoreboard\node>
```

Any idea about the error?

**Comment by Pezmc** [comment]
I'm unable to reproduce on Linux with node.js v9.2.1, so it may be a problem on Windows 10, are you able to provide any more information?

```console
$ node server.js
   info  - socket.io started
Listening on port 25565
   info  - handshake authorized FmeakcCPBkALICUFgSva
   info  - handshake authorized J83yTjGediBux2u-gSvb
```

**Comment by RDCH106** [comment]
@Pezmc  What kind of information do you need?

**Comment by Pezmc** [comment]
Can you try updating socket.io? It might be a problem with the library on windows!

**Comment by RDCH106** [comment]
I am using the last version...

Maybe downgrading the version of socket.io ... Wich version are you using in Linux?

**Comment by Pezmc** [comment]
Thank you for sharing @reg-is, I did start a branch to update Socket.io but it turned out more involved than I expected!
